name: Flutter CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  # ========== ANDROID ==========
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: mkdir -p artifacts
      - run: |

          flutter build apk --release --split-per-abi
          (cd ./build/app/outputs/flutter-apk/ && {
            mv ./app-arm64-v8a-release.apk "artifacts/$APP_NAME-$app_ver-arm64-v8a.apk"
            mv ./app-armeabi-v7a-release.apk "artifacts/$APP_NAME-$app_ver-armeabi-v7a.apk"
            mv ./app-x86_64-release.apk "artifacts/$APP_NAME-$app_ver-x86_64.apk"
          })

          flutter build apk --release
          (cd ./build/app/outputs/flutter-apk/ &&
            mv ./app-release.apk "artifacts/$APP_NAME-$app_ver-universal.apk"
          )

      - name: Upload Android Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/*
        env:
          APP_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  # ========== IOS ==========
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - name: Build unsigned iOS IPA
        run: |
          flutter build ios --release --no-codesign
          mkdir artifacts
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app-unsigned.ipa Payload
          mv app-unsigned.ipa ../../../artifacts/

      - name: Upload iOS Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  # ========== WEB ==========
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
